config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :admins
  root 'posts#index'

  resources :posts do
    resource :map
    resources :charges
    resources :likes
  end

  resources :tags

  resources :orders
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
  validates :user_id, uniqueness: {scope: :post_id}
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image,
	                  styles: { thumb: '300x300>' },
                    storage: :s3,
    								s3_credentials: {
							      bucket: 'instagrammer_may',
							      access_key_id: Rails.application.secrets.s3_access_key,
							      secret_access_key: Rails.application.secrets.s3_secret_key
    }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_and_belongs_to_many :tags
  has_many :likes

  def tag_names
    ''
  end

  def tag_names=(tag_list)
  	# self.tags << Tag.create(name: tag_list)
    tag_list.split(/\s,?/).each do |tag|
      tags << Tag.find_or_create_by(name: tag)
    end
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :posts
	validates :name, uniqueness: true

	def to_param
		name
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
		@post = Post.find params[:post_id]
	end

	def create
		@post = Post.find params[:post_id]

	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	    :email => params[:stripeEmail],
	    :card  => params[:stripeToken]
	  )

	  charge = Stripe::Charge.create(
	    :customer    => customer.id,
	    :amount      => @amount,
	    :description => "Print of #{@post.title}",
	    :currency    => 'usd'
	  )

	  Order.create(user: current_user, post: @post)

	  flash[:notice] = 'Thanks for your payment'
	  redirect_to posts_path

	rescue Stripe::CardError => e
	  flash[:error] = e.message
	  redirect_to charges_path
	end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

	def create
	  @post = Post.find params[:post_id]
	  @post.likes.create!

	  WebsocketRails[:likes].trigger 'new', { id: @post.id, new_like_count: @post.likes.count }

	  redirect_to '/posts'
	rescue
		render json: {message: 'cannot like twice'}
	end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
	def show
		@post = Post.find params[:post_id]
	end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	before_action :authenticate_admin!
	def index
		@orders = Order.all
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, except: [:index]

	def index
		@posts = Post.all.order(created_at: :desc)
	end

	def new
		@post = Post.new
	end

	def create
		@post = Post.new params[:post].permit(:title, :body, :image, :tag_names, :address)
		@post.user = current_user
		@post.save!

		redirect_to posts_path
	end

	def show
		@post = Post.find params[:id]
	end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	def show
		@tag = Tag.find_by_name params[:id]
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/charges/new.html.erb
<div class='container'>
	<%= form_tag post_charges_path(@post) do %>
	  <article>
	    <label class="amount">
	      <span>Amount: $5.00</span>
	    </label>
	  </article>

	  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
	          data-key="<%= Rails.application.secrets.stripe_public_key %>"
	          data-description="A month's subscription"
	          data-amount="500"></script>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Instagrammer</title>
  	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <script src='http://maps.google.com/maps/api/js?sensor=true'></script>
  	<%= javascript_include_tag 'application' %>
  	<%= csrf_meta_tags %>
  </head>

  <body>

    <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to 'Instagrammer', root_path, class: 'navbar-brand' %>
        </div>
        <div class="navbar-collapse collapse">
        <% if current_user %>
        <p class='navbar-form navbar-right navbar-text'>Welcome <%= current_user.email %>
        <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: 'btn btn-success' %>
        </p>
        <% else %>
          <%= form_for(User.new, as: :user, url: session_path(:user), html: { class: 'navbar-form navbar-right' }) do |f| %>
            <div class="form-group">
              <%= f.email_field :email, placeholder: 'Email', class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
            </div>

            <%= f.button "Sign in", class: 'btn btn-success' %>
            <% end %>
          <% end %>

        </div><!--/.navbar-collapse -->
      </div>
    </div>

    <% if notice %>
      <p class="alert alert-success alert-dismissible">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= notice %>
      </p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger alert-dismissible">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= alert %>
      </p>
    <% end %>
		<%= yield %>

    <div class='container'>
      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->
    </div>


  </body>
</html>

app/views/maps/show.html.erb
<div class='container'>
	<h1>Here's where your picture was taken</h1>
	<div id='map' data-id=<%= @post.id %>></div>
</div>

app/views/orders/index.html.erb
<div class='container'>
	<% unless @orders.any? %>
		<h1>No orders yet</h1>
	<% else %>
		<h1>Current orders:</h1>
		<ul>
			<% @orders.each do |order| %>
				<li>
					<p><%= order.post.title %></p>
					<p>Ordered by <strong><%= order.user.email %></strong></p>
				</li>
			<% end %>
	<% end %>
</div>

app/views/posts/_post.html.erb
<div class='col-sm-4'>

	<!-- panel -->
	<div class="panel panel-default">
	 	
	 	<!-- title of the post -->
	 	<div class="panel-heading">
    	<h3 class="panel-title"><%= post.title %></h3>
  	</div>

  	<!-- body -->
  	<div class="panel-body">
	  	<!-- image only if present -->
	    <p>
			<% if post.image.present? %>	
				<%= image_tag post.image.url(:thumb), class: 'uploaded-pic' %>
			<% end %>
			</p>

			<!-- description -->
			<p>
				<%= post.body %>
			</p>

			<!-- tags -->
			<p>
				<% post.tags.each do |tag| %>
					<%= link_to tag.name, tag_path(tag) %>
				<% end %>
			</p>

			<!-- map link showing only if present -->
			<% unless post.address.blank? %>
				<p>
					<%= link_to 'Map', post_map_path(post), class: 'btn btn-info' %>
			<% end %>

			<!-- payment -->
				<%= link_to 'Buy', new_post_charge_path(post), class: 'btn btn-warning' %>

			<!-- likes -->
				<%= link_to "❤ #{post.likes.count}", post_likes_path(post), class: 'btn btn-primary like-btn', data: { 'post-id' => post.id } %>
			</p>

  	</div>

	  	<!-- creator of the post -->
  	<div class='panel-footer'>
			Posted by: <%= post.user.email %>
		</div>
	</div>
	<!-- end panel -->

</div>

app/views/posts/index.html.erb
<% unless signed_in? %>
    <div class="jumbotron">
      <div class="container">
        <h1>Welcome to Instagrammer</h1>
        <p>This is a project created on the 9th and 10th weeks of <a href='http://www.makersacademy.com' target='_blank'>Makers Academy</a>, a 12 weeks coding bootcamp in Shoreditch, London</p>
        <p>
        	<%= link_to 'Sign up »', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
		</p>
      </div>
    </div>
<% end %>

<div class='container'>
	<!-- new post -->
	<p><%= link_to 'New post', new_post_path, class: 'btn btn-success btn-lg' %></p>

	<% if @posts.none? %>
		<h1>No posts yet</h1>
	<% else %>
		<% @posts.in_groups_of(3, false).each do |post_triplet| %>
			<div class='row'>
					<%= render post_triplet %>
			</div>
		<% end %>
	<% end %>
</div>

app/views/posts/new.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %>
		<%= f.text_area :body %>
	</p>
	<p>
		<%= f.label :image %>
		<%= f.file_field :image %>
	</p>

	<p>
		<%= f.label :address %>
		<%= f.text_field :address %>
	</p>

	<p>
		<%= f.label :tag_names, 'Tags' %>
		<%= f.text_field :tag_names%>
	</p>

	<p><%= f.submit 'Post' %></p>
<% end %>

app/views/tags/show.html.erb
<div class='container'>
	<h1>
		Posts associated with <%= @tag.name %>
	</h1>
	
	<div class='row'>
		<%= render @tag.posts %>
	</div>
</div>